-- Database: lab

CREATE TABLE orders(
	order_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	order_uid uuid NOT NULL,
	customer_code varchar(50) NOT NULL,
	description text NULL,
	status_flag boolean NOT NULL,
	quantity int NOT NULL,
	unit_price numeric(19,4) NOT NULL,
	discount_pct decimal(5, 2) NOT NULL,
	-- TODO(mog): computed column line_total was 'AS (quantity*unit_price)'. Postgres needs a type: line_total <type> GENERATED ALWAYS AS (quantity*unit_price) STORED. Column dropped.
	notes text NULL,
	payload bytea NULL,
	created_at timestamp NOT NULL,
	updated_at timestamptz NULL,
	legacy_ts timestamp NULL
);

ALTER TABLE orders ADD CONSTRAINT PK_orders PRIMARY KEY
(
	order_id
);

ALTER TABLE orders ADD CONSTRAINT UQ_orders_code UNIQUE
(
	customer_code
);

CREATE INDEX IX_orders_status ON orders
(
	status_flag
)
INCLUDE ( 	customer_code);

alter table orders alter column order_uid set default gen_random_uuid();

-- TODO(mog): if status_flag was BIT (now boolean), change this default to true/false
alter table orders alter column status_flag set default (0);

-- TODO(mog): if quantity was BIT (now boolean), change this default to true/false
alter table orders alter column quantity set default (1);

alter table orders alter column discount_pct set default (0.00);

alter table orders alter column created_at set default CURRENT_TIMESTAMP;

ALTER TABLE orders ADD CONSTRAINT CK_orders_qty CHECK ((quantity>(0)));

COMMENT ON COLUMN orders.customer_code IS 'Business customer code';

COMMENT ON TABLE orders IS 'Customer orders fact table';

