create or replace TABLE INVOICE (
	INVOICE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1,
	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	primary key (INVOICE_ID)
);

create or replace TABLE POLICY_HOLDER (
	POLICY_HOLDER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1,
	ACCOUNT_CODE VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(255) COMMENT 'primary contact email',
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	SIGNED_UP_ON DATE NOT NULL,
	NOTES STRING,
	BALANCE NUMBER(18,2) NOT NULL,
	LAST_SEEN_AT TIMESTAMP_LTZ(9)
)COMMENT='account master table'
cluster by (ACCOUNT_CODE);

create or replace TABLE LEDGER_ENTRY (
	EVENT_ID NUMBER(38,0) NOT NULL,
	SEQ_NO NUMBER(9,0) NOT NULL,
	RETRY_COUNT NUMBER(3,0),
	AMOUNT NUMBER(18,2) NOT NULL,
	RATE FLOAT,
	IS_SAMPLED BOOLEAN NOT NULL,
	EVENT_DATE DATE NOT NULL,
	INGESTED_AT TIMESTAMP_NTZ(9) NOT NULL,
	OCCURRED_AT TIMESTAMP_TZ(9) NOT NULL,
	SYNCED_AT TIMESTAMP_LTZ(9),
	SOURCE_NAME VARCHAR(120) NOT NULL,
	RAW_BODY STRING,
	PAYLOAD VARIANT,
	TAGS ARRAY,
	CONTEXT OBJECT,
	CHECKSUM BINARY(32)
);
