CREATE OR REPLACE TABLE CUSTOMERS (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	BALANCE DECIMAL(18,2),
	ATTRS STRING,
	CREATED_AT TIMESTAMP_NTZ,
	UPDATED_AT TIMESTAMP,
	REGION VARCHAR(50),
	constraint PK_CUSTOMERS primary key (ID)
)
-- TODO(mog): dropped Snowflake CLUSTER BY (REGION) (set target clustering/partitioning manually)
