CREATE OR REPLACE TABLE CUSTOMERS (
	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	BALANCE DECIMAL(18,2),
	ATTRS JSON,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ,
	REGION VARCHAR(50)
)
-- TODO(mog): dropped Snowflake CLUSTER BY (REGION) (DuckDB has no clustering)
