
  CREATE TABLE "SYSTEM"."ORA2SF_ORDERS" 
   (	"ORDER_ID" NUMBER(38,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"QUANTITY" NUMBER(10,0) DEFAULT 0, 
	"UNIT_PRICE" NUMBER(12,2) NOT NULL ENABLE, 
	"DISCOUNT_PCT" NUMBER(5,4), 
	"TOTAL_AMOUNT" NUMBER(14,2) GENERATED ALWAYS AS ("QUANTITY"*"UNIT_PRICE") VIRTUAL , 
	"DESCRIPTION" CLOB, 
	"NOTES" VARCHAR2(4000), 
	"PAYLOAD" BLOB, 
	"CHECKSUM" RAW(16), 
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6), 
	"SHIP_TS" TIMESTAMP (6) WITH TIME ZONE, 
	"LOCAL_TS" TIMESTAMP (9) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CK_ORA2SF_QTY" CHECK (quantity >= 0) ENABLE, 
	 CONSTRAINT "PK_ORA2SF_ORDERS" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_ORA2SF_ORDER_NO" UNIQUE ("ORDER_NO")
  USING INDEX  ENABLE
   ) 