CREATE TABLE ORA2DD_ORDERS 
-- TODO(mog): Oracle IDENTITY dropped; create a DuckDB SEQUENCE and set DEFAULT nextval('seq') on this column for auto-increment
   (	ORDER_ID BIGINT  NOT NULL, 
-- TODO(mog): Oracle sequence DEFAULT (seq.NEXTVAL) dropped; create a DuckDB SEQUENCE and set DEFAULT nextval('seq') if you need it
	LEGACY_ID BIGINT NOT NULL, 
	CUSTOMER_NO BIGINT NOT NULL, 
	SKU VARCHAR(64) NOT NULL, 
	DESCRIPTION VARCHAR(4000), 
	NOTES VARCHAR, 
	QTY BIGINT DEFAULT 1 NOT NULL, 
	UNIT_PRICE DECIMAL(18,4) NOT NULL, 
	DISCOUNT_PCT DECIMAL(5,2) DEFAULT 0, 
	LINE_TOTAL DECIMAL(20,4) GENERATED ALWAYS AS (QTY*UNIT_PRICE*(1-DISCOUNT_PCT/100)) VIRTUAL , 
	IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL, 
	STATUS VARCHAR(20) DEFAULT 'NEW' NOT NULL, 
	PAYLOAD BLOB, 
	DOC_BLOB BLOB, 
	CREATED_AT TIMESTAMP DEFAULT current_timestamp NOT NULL, 
	UPDATED_AT TIMESTAMP DEFAULT current_timestamp, 
	EVENT_TS TIMESTAMPTZ, 
	 CONSTRAINT ORA2DD_ORDERS_QTY_CK CHECK (qty > 0), 
	 CONSTRAINT ORA2DD_ORDERS_DISC_CK CHECK (discount_pct >= 0 AND discount_pct <= 100), 
	 CONSTRAINT ORA2DD_ORDERS_PK PRIMARY KEY (ORDER_ID)
  , 
	 CONSTRAINT ORA2DD_ORDERS_UQ UNIQUE (SKU, CUSTOMER_NO)
  ) 