//! Golden tests for the `tests/sql/MSSQL-To-PGSQL-Table.mog` conversion script,
//! run against its `.sql` fixtures. Expected outputs live beside the fixtures as
//! `*.pgsql`. EOL is normalized to LF before comparison so git's autocrlf handling
//! can't make these flaky.

use std::collections::BTreeMap;
use std::path::PathBuf;

use mog::{execute_at, parse_mog, parse_mog_with_defines};

// The converter recipe, its `.sql`/`.pgsql` fixtures, and the broader schema
// inputs all live in `tests/sql/`.
fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/sql")
        .join(rel)
}

/// The tests/sql dir, used as the base dir so `run_mog` can resolve sibling scripts.
fn fixture_dir() -> PathBuf {
    fixture("")
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(fixture(rel)).unwrap_or_else(|e| panic!("read {rel}: {e}"))
}

fn lf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\r', "\n")
}

fn convert(input_rel: &str) -> String {
    let script = read("MSSQL-To-PGSQL-Table.mog");
    let input = read(input_rel);
    let mog = parse_mog(&script).expect("parse MSSQL-To-PGSQL-Table.mog");
    execute_at(&mog, &input, Some(fixture_dir().as_path())).expect("execute conversion")
}

#[test]
fn golden_shopdemo_schema() {
    let out = convert("MSSQL-To-PGSQL-Table.TestInput.sql");
    let expected = read("MSSQL-To-PGSQL-Table.TestExpectedOutput.pgsql");
    assert_eq!(
        lf(&out),
        lf(&expected),
        "ShopDemo schema conversion drifted"
    );
}

#[test]
fn golden_type_zoo() {
    let out = convert("example-mssql-types.sql");
    let expected = read("example-mssql-types.pgsql");
    assert_eq!(
        lf(&out),
        lf(&expected),
        "TypeZoo type-map conversion drifted"
    );
}

#[test]
fn schema_prefix_default_strips_dbo() {
    let out = lf(&convert("MSSQL-To-PGSQL-Table.TestInput.sql"));
    assert!(
        out.contains("CREATE TABLE Categories("),
        "expected unqualified table name"
    );
    assert!(!out.contains("dbo."), "dbo. should be stripped by default");
    // Sanity: the noisy T-SQL artifacts are gone and terminators are Postgres ';'.
    assert!(
        !out.contains("\nGO\n") && !out.contains('['),
        "GO/brackets should be gone"
    );
    assert!(
        !out.to_lowercase().contains("identity(1,1)"),
        "IDENTITY(1,1) should be rewritten"
    );
}

#[test]
fn schema_prefix_override_qualifies() {
    let script = read("MSSQL-To-PGSQL-Table.mog");
    let input = read("MSSQL-To-PGSQL-Table.TestInput.sql");
    let mut defines = BTreeMap::new();
    defines.insert("schema_prefix".to_string(), "public.".to_string());
    let mog = parse_mog_with_defines(&script, &defines).expect("parse with --define");
    let out = lf(&execute_at(&mog, &input, Some(fixture_dir().as_path())).expect("execute"));
    assert!(
        out.contains("CREATE TABLE public.Categories("),
        "expected public.-qualified name"
    );
    assert!(!out.contains("dbo."), "dbo. should be replaced, not kept");
}

#[test]
fn converts_table_features() {
    let out = lf(&convert("table-features.sql"));

    // Identity with a non-(1,1) seed/step becomes a parameterized IDENTITY.
    assert!(
        out.contains("GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 5)"),
        "IDENTITY(1000,5) not generalized:\n{out}"
    );
    // Column markers with no Postgres equivalent are stripped.
    assert!(!out.contains("ROWGUIDCOL"), "ROWGUIDCOL not stripped");
    assert!(!out.contains("SPARSE"), "SPARSE not stripped");
    assert!(
        !out.contains("NOT FOR REPLICATION"),
        "NOT FOR REPLICATION not stripped"
    );
    // Sequence functions map to Postgres.
    assert!(
        out.contains("set default gen_random_uuid()"),
        "newsequentialid() not mapped"
    );
    assert!(
        out.contains("set default nextval('FeatureSeq')"),
        "NEXT VALUE FOR not mapped"
    );
    // Computed columns are left as-is (documented manual case: PG needs an
    // explicit type and STORED). Guard that we did not silently mangle them.
    assert!(
        out.contains("TotalWithTax AS (Total * 1.1) PERSISTED"),
        "computed column unexpectedly changed:\n{out}"
    );
}

#[test]
fn converts_standalone_indexes() {
    let out = lf(&convert("indexes.sql"));

    // CLUSTERED/NONCLUSTERED and the storage-option noise are gone.
    for gone in [
        "NONCLUSTERED",
        "CLUSTERED",
        "WITH (PAD_INDEX",
        "ON PRIMARY",
        "[",
        " ASC",
    ] {
        assert!(
            !out.contains(gone),
            "index conversion left `{gone}`:\n{out}"
        );
    }
    // A covering index keeps INCLUDE (valid Postgres), tidied spacing.
    assert!(
        out.contains("CREATE INDEX IX_Thing_Name ON Thing"),
        "plain index missing:\n{out}"
    );
    assert!(
        out.contains("INCLUDE (Email,CreatedAt)"),
        "INCLUDE not kept"
    );
    // A filtered unique index keeps its WHERE as a Postgres partial index.
    assert!(
        out.contains("CREATE UNIQUE INDEX UX_Thing_Code ON Thing"),
        "unique index missing"
    );
    assert!(
        out.contains("WHERE (IsActive=(1))"),
        "filter predicate dropped"
    );
    // A clustered index becomes a plain index (Postgres has no clustered form).
    assert!(
        out.contains("CREATE INDEX IX_Thing_Placed ON Thing (PlacedAt)"),
        "clustered index not converted:\n{out}"
    );
}

#[test]
fn strips_server_noise() {
    let script = read("mssql-strip-server-noise.mog");
    let input = read("mssql-strip-server-noise.TestInput.sql");
    let mog = parse_mog(&script).expect("parse strip-server-noise.mog");
    let out = lf(&execute_at(&mog, &input, Some(fixture_dir().as_path())).expect("execute"));

    // Server / session / DROP scaffolding is gone.
    for needle in [
        "ALTER DATABASE",
        "CREATE DATABASE",
        "DROP DATABASE",
        "DROP TABLE",
        "DROP INDEX",
        "DROP CONSTRAINT",
        "CHECK CONSTRAINT [CK_Widget_Name]", // the re-enable line
        "sp_addextendedproperty",
        "sp_dropextendedproperty",
        "sp_db_vardecimal",
        "SET ANSI_NULLS",
        "SET QUOTED_IDENTIFIER",
        "SET ANSI_PADDING",
        "Object:  Table", // SSMS banner
        "IF  EXISTS",
    ] {
        assert!(
            !out.contains(needle),
            "stripper left `{needle}` behind:\n{out}"
        );
    }

    // Real object DDL survives (still bracketed; the stripper does not convert).
    assert!(
        out.contains("CREATE TABLE [dbo].[Widget]"),
        "CREATE TABLE was removed"
    );
    assert!(
        out.contains("CREATE NONCLUSTERED INDEX [IX_Widget_Name]"),
        "CREATE INDEX was removed"
    );
    assert!(
        out.contains("WITH CHECK ADD  CONSTRAINT [CK_Widget_Name]"),
        "the ADD CONSTRAINT line was removed"
    );
}
