//! Golden test for the `tests/sql/MySQL-To-PGSQL.mog` converter against its
//! mysqldump fixture. Uses `execute_at` with `tests/sql/` as the base dir so the
//! composed `mysql-strip-dump-noise.mog` resolves.

use std::path::PathBuf;

use mog::{execute_at, parse_mog};

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/sql")
        .join(rel)
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(fixture(rel)).unwrap_or_else(|e| panic!("read {rel}: {e}"))
}

fn lf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\r', "\n")
}

fn convert() -> String {
    let script = read("MySQL-To-PGSQL.mog");
    let input = read("MySQL-To-PGSQL.TestInput.sql");
    let mog = parse_mog(&script).expect("parse MySQL-To-PGSQL.mog");
    let root = fixture("");
    execute_at(&mog, &input, Some(root.as_path())).expect("execute conversion")
}

#[test]
fn golden_shopmysql() {
    let out = convert();
    let expected = read("MySQL-To-PGSQL.TestExpectedOutput.pgsql");
    assert_eq!(lf(&out), lf(&expected), "mysqldump conversion drifted");
}

#[test]
fn key_conversions() {
    let out = lf(&convert());

    // Dump scaffolding is gone.
    for gone in [
        "`",
        "ENGINE=",
        "AUTO_INCREMENT=",
        "unsigned",
        " enum(",
        "/*!",
        "DELIMITER",
        "LOCK TABLES",
        "ON UPDATE CURRENT_TIMESTAMP",
    ] {
        assert!(!out.contains(gone), "converter left `{gone}`:\n{out}");
    }

    // Types and identity mapped.
    assert!(
        out.contains("GENERATED BY DEFAULT AS IDENTITY"),
        "AUTO_INCREMENT not mapped"
    );
    assert!(
        out.contains("is_active boolean"),
        "tinyint(1) not -> boolean"
    );
    assert!(out.contains("metadata jsonb"), "json not -> jsonb");
    assert!(
        out.contains("weight_kg double precision"),
        "double not mapped"
    );
    assert!(out.contains("thumbnail bytea"), "blob not -> bytea");

    // ENUM -> varchar + inline CHECK reusing the column name.
    assert!(
        out.contains("status varchar CHECK (status IN ('active','inactive','pending'))"),
        "enum not converted:\n{out}"
    );

    // Generated column survives (backticks and introducers cleaned).
    assert!(
        out.contains("full_name varchar(201) GENERATED ALWAYS AS (concat_ws(' ',first_name,last_name)) STORED"),
        "generated column mangled:\n{out}"
    );

    // Inline indexes hoisted to standalone statements (hoist_from_block).
    assert!(out.contains("CREATE UNIQUE INDEX uq_products_sku ON products (sku);"));
    assert!(out.contains("CREATE INDEX idx_customers_status ON customers (status);"));
    assert!(out.contains("CREATE INDEX ft_products_title ON products (title,description);"));

    // FK with actions stays inline (valid Postgres).
    assert!(
        out.contains("ON DELETE CASCADE ON UPDATE CASCADE"),
        "FK actions dropped"
    );

    // The non-immutable generated column is flagged for review (not silently
    // left to fail at load time).
    assert!(
        out.contains("STORED, -- FIXME(mog): generated expression must be IMMUTABLE"),
        "generated column not flagged:\n{out}"
    );
}
