CREATE TABLE CUSTOMERS
   (	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	DESCRIPTION TEXT,
	BALANCE NUMERIC(18,2),
	IS_ACTIVE SMALLINT,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	 CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
  )
