
  CREATE TABLE "APP"."CUSTOMERS"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(200),
	"EMAIL" VARCHAR2(255),
	"DESCRIPTION" CLOB,
	"BALANCE" NUMBER(18,2),
	"IS_ACTIVE" NUMBER(1,0),
	"CREATED_AT" DATE,
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
