CREATE TABLE CUSTOMERS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	BALANCE DECIMAL(18,2),
	ATTRS JSON,
	CREATED_AT DATETIME,
	UPDATED_AT TIMESTAMP,
	REGION VARCHAR(50),
	constraint PK_CUSTOMERS primary key (ID)
)
-- TODO(mog): dropped Snowflake CLUSTER BY (REGION) (set target clustering/partitioning manually)
