--
-- PostgreSQL database dump
--

\restrict FIXEDTOKENabc123FIXEDTOKENabc123FIXEDTOKENabc123FIXED

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pg2ch_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pg2ch_orders (
    id bigint NOT NULL,
    order_ref uuid DEFAULT gen_random_uuid() NOT NULL,
    customer_code character varying(32) NOT NULL,
    description text,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    discount double precision,
    weight_kg real,
    is_paid boolean DEFAULT false NOT NULL,
    status_code smallint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone,
    order_date date,
    metadata jsonb,
    payload bytea
);


--
-- Name: pg2ch_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pg2ch_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pg2ch_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pg2ch_orders pg2ch_orders_customer_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg2ch_orders
    ADD CONSTRAINT pg2ch_orders_customer_code_key UNIQUE (customer_code);


--
-- Name: pg2ch_orders pg2ch_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg2ch_orders
    ADD CONSTRAINT pg2ch_orders_pkey PRIMARY KEY (id);


--
-- Name: pg2ch_orders_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pg2ch_orders_created_at_idx ON public.pg2ch_orders USING btree (created_at);


--
-- PostgreSQL database dump complete
--

\unrestrict FIXEDTOKENabc123FIXEDTOKENabc123FIXEDTOKENabc123FIXED

