CREATE TABLE CUSTOMERS
   (	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	DESCRIPTION LONGTEXT,
	BALANCE DECIMAL(18,2),
	IS_ACTIVE TINYINT(1),
	CREATED_AT DATETIME,
	UPDATED_AT DATETIME(6),
	 CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
  )
