CREATE TABLE CUSTOMERS (
	ID BIGINT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(200),
	EMAIL VARCHAR(255),
	BALANCE DECIMAL(18,2),
	ATTRS SUPER,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ,
	REGION VARCHAR(50),
	constraint PK_CUSTOMERS primary key (ID)
)
-- TODO(mog): dropped Snowflake CLUSTER BY (REGION) (set target clustering/partitioning manually)
