CREATE OR REPLACE TABLE CUSTOMERS
   (	ID INT64 NOT NULL,
	NAME STRING(200),
	CODE STRING(50),
	GRADE STRING(1),
	DESCRIPTION STRING,
	BALANCE NUMERIC(18,2),
	RATE FLOAT64,
	IS_ACTIVE INT64,
	PAYLOAD BYTES,
	CHECKSUM BYTES(16),
	CREATED_AT DATETIME,
	UPDATED_AT DATETIME,
	EVENT_AT TIMESTAMP,
	 CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID) NOT ENFORCED
  )
