
  CREATE TABLE "APP"."CUSTOMERS"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(200),
	"CODE" NVARCHAR2(50),
	"GRADE" CHAR(1),
	"DESCRIPTION" CLOB,
	"BALANCE" NUMBER(18,2),
	"RATE" BINARY_DOUBLE,
	"IS_ACTIVE" NUMBER(1,0),
	"PAYLOAD" BLOB,
	"CHECKSUM" RAW(16),
	"CREATED_AT" DATE,
	"UPDATED_AT" TIMESTAMP (6),
	"EVENT_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
