-- Database: ShopDemo

CREATE TABLE TypeZoo(
	Id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Name varchar(200) NOT NULL,
	Code char(10) NULL,
	Notes text NULL,
	Body text NULL,
	Price numeric(19,4) NOT NULL,
	Discount numeric(10,4) NULL,
	Weight double precision NULL,
	Photo bytea NULL,
	Hash bytea NULL,
	Flags bytea NULL,
	CreatedAt timestamp NOT NULL,
	UpdatedAt timestamptz NULL,
	LegacyAt timestamp NULL,
 CONSTRAINT PK_TypeZoo PRIMARY KEY
(
	Id
)
);

alter table TypeZoo alter column CreatedAt set default (now() at time zone 'utc');

