/****** Object:  Index [IX_Thing_Name]    Script Date: 1/2/2024 3:04:05 PM ******/
CREATE NONCLUSTERED INDEX [IX_Thing_Name] ON [dbo].[Thing]
(
	[Name] ASC
)
INCLUDE([Email],[CreatedAt]) WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UX_Thing_Code] ON [dbo].[Thing]
(
	[Code] ASC
)
WHERE ([IsActive]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [IX_Thing_Placed] ON [dbo].[Thing] ([PlacedAt] ASC)
GO
