-- Database: ShopDemo

CREATE TABLE Categories(
	CategoryID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	Name varchar(100) NOT NULL,
	SortOrder smallint NOT NULL,
	IsActive boolean NOT NULL,
	CreatedAt timestamp NOT NULL,
 CONSTRAINT PK_Categories PRIMARY KEY
(
	CategoryID
)
);

CREATE TABLE Customers(
	CustomerID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CustomerGuid uuid NOT NULL,
	Email varchar(255) NOT NULL,
	FirstName varchar(100) NOT NULL,
	LastName varchar(100) NOT NULL,
	Status smallint NOT NULL,
	Notes text NULL,
	LastLogin timestamp NULL,
	CreatedAt timestamp NOT NULL,
 CONSTRAINT PK_Customers PRIMARY KEY
(
	CustomerID
),
 CONSTRAINT IX_Customers_Email UNIQUE
(
	Email
)
);

CREATE TABLE Products(
	ProductID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CategoryID int NOT NULL,
	Sku varchar(40) NOT NULL,
	Name varchar(200) NOT NULL,
	Description text NULL,
	Price numeric(19, 4) NOT NULL,
	Status smallint NOT NULL,
	CreatedAt timestamp NOT NULL,
 CONSTRAINT PK_Products PRIMARY KEY
(
	ProductID
)
);

CREATE TABLE Orders(
	OrderID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	OrderGuid uuid NOT NULL,
	CustomerID int NOT NULL,
	OrderNumber varchar(32) NOT NULL,
	Status smallint NOT NULL,
	TotalAmount numeric(19, 4) NOT NULL,
	PlacedAt timestamp NOT NULL,
	ShippedAt timestamp NULL,
 CONSTRAINT PK_Orders PRIMARY KEY
(
	OrderID
)
);

CREATE TABLE OrderItems(
	OrderItemID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	OrderID int NOT NULL,
	ProductID int NOT NULL,
	Quantity int NOT NULL,
	UnitPrice numeric(19, 4) NOT NULL,
 CONSTRAINT PK_OrderItems PRIMARY KEY
(
	OrderItemID
)
);

alter table Categories alter column SortOrder set default (0);

alter table Categories alter column IsActive set default (1);

alter table Categories alter column CreatedAt set default CURRENT_TIMESTAMP;

alter table Customers alter column CustomerGuid set default gen_random_uuid();

alter table Customers alter column Status set default (0);

alter table Customers alter column CreatedAt set default CURRENT_TIMESTAMP;

alter table Products alter column Price set default (0);

alter table Products alter column Status set default (1);

alter table Products alter column CreatedAt set default CURRENT_TIMESTAMP;

alter table Orders alter column Status set default (0);

alter table Orders alter column TotalAmount set default (0);

alter table Orders alter column PlacedAt set default CURRENT_TIMESTAMP;

alter table OrderItems alter column Quantity set default (1);

ALTER TABLE Products ADD CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryID)
REFERENCES Categories (CategoryID);

ALTER TABLE Orders ADD CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerID)
REFERENCES Customers (CustomerID);

ALTER TABLE OrderItems ADD CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderID)
REFERENCES Orders (OrderID);

ALTER TABLE OrderItems ADD CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductID)
REFERENCES Products (ProductID);

