USE [MogConvertTest]
GO
CREATE TABLE [dbo].[Widget](
	[WidgetID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Widget] PRIMARY KEY CLUSTERED
(
	[WidgetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Widget_Name] ON [dbo].[Widget]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Widget]  WITH CHECK ADD  CONSTRAINT [CK_Widget_Name] CHECK  ((len([Name])>(0)))
GO
