
CREATE TABLE categories (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100) NOT NULL,
  slug varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT '1',
  sort_order smallint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uq_categories_slug ON categories (slug);

CREATE TABLE customers (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email varchar(255) NOT NULL,
  first_name varchar(100) DEFAULT NULL,
  last_name varchar(100) DEFAULT NULL,
  full_name varchar(201) GENERATED ALWAYS AS (concat_ws(' ',first_name,last_name)) STORED, -- FIXME(mog): generated expression must be IMMUTABLE for Postgres (e.g. rewrite concat_ws with ||)
  status varchar CHECK (status IN ('active','inactive','pending')) NOT NULL DEFAULT 'pending',
  roles text DEFAULT NULL,
  balance decimal(12,2) NOT NULL DEFAULT '0.00',
  metadata jsonb DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX idx_customers_status ON customers (status);
CREATE UNIQUE INDEX uq_customers_email ON customers (email);

CREATE TABLE orders (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id bigint NOT NULL,
  order_no varchar(32) NOT NULL,
  status varchar CHECK (status IN ('cart','placed','shipped','cancelled')) NOT NULL DEFAULT 'cart',
  total decimal(12,2) NOT NULL DEFAULT '0.00',
  placed_at timestamp DEFAULT NULL,
  note text,
  PRIMARY KEY (id),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE UNIQUE INDEX uq_orders_no ON orders (order_no);

CREATE TABLE products (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  category_id int NOT NULL,
  sku char(12) NOT NULL,
  title varchar(200) NOT NULL,
  description text,
  price decimal(10,2) NOT NULL DEFAULT '0.00',
  weight_kg double precision DEFAULT NULL,
  in_stock boolean NOT NULL DEFAULT '1',
  thumbnail bytea,
  flags bit(8) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX ft_products_title ON products (title,description);
CREATE UNIQUE INDEX uq_products_sku ON products (sku);

