CREATE TABLE products (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sku varchar(40) NOT NULL,
  name varchar(200),
  description text,
  price decimal(18,2) DEFAULT '0.00',
  in_stock BOOLEAN DEFAULT '1',
  attrs JSONB,
  status TEXT DEFAULT 'active', -- TODO(mog): MySQL ENUM mapped to TEXT; the allowed-value constraint was lost (use a CHECK or a Postgres ENUM type)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP, -- TODO(mog): MySQL ON UPDATE auto-refresh dropped; no portable equivalent (use a trigger/stream/task)
  PRIMARY KEY (id)
)
